logging:
  level:
    br:
      com:
        mesquitadev:
          estoque: DEBUG
spring:
  profiles:
    active: production
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        dialect: org.hibernate.dialect.H2Dialect
        generate_statistics: true
        connection:
          autocommit: false
    open-in-view: false
    show-sql: true
  datasource:
    username: sa
    password: password
    url: jdbc:h2:mem:testdb
    hikari:
      auto-commit: false
      connection-timeout: 250
      max-lifetime: 600000
      maximum-pool-size: 20
      minimum-idle: 10
      pool-name: master
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: '8443'  
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false